pipeline {
	agent any
	stages{
		stage("Build") {
			steps{
				sh "is already build it"
			}

		}
		stage('Docker Compose Up'){
			steps{
				sh "docker-compose -f docker-compose.yml up -d --build"
			}

		}
	}

}